

homeassistant:



##################################################
## Inputs
##################################################

input_select:
  ha_mode:
    name: Mode
    icon: mdi:account-circle
    options:
     - Normal
     - Visitors
     - Show off
     - Developer
    initial: Normal



##################################################
## Switchs
##################################################

switch:
  - platform: template
    switches:
      mode_developer:
        value_template: "{{ is_state('input_select.ha_mode', 'Developer') }}"
        turn_on:
          - service: script.mode_developer
        turn_off:
          - service: script.mode_normal

          
##################################################
## Scripts
##################################################

script:

  # Mode Developer
  mode_developer:
    alias: Start Developer mode
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.ha_mode
          option: Developer
      - service: group.set_visibility
        entity_id: group.developer
        data:
          visible: True

  # Mode Normal. Called in Startup (config/packages/ha_triggers.yaml)
  mode_normal:
    alias: Back to Normal mode
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.ha_mode
          option: Normal
      - service: group.set_visibility
        entity_id: group.developer
        data:
          visible: False
