homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

######################################################################################################################    
#  https://home-assistant.io/docs/configuration/packages/
######################################################################################################################       
  packages: !include_dir_named config/packages/
 
######################################################################################################################    
#  CUSTOMIZE
###################################################################################################################### 
  customize: !include customize.yaml    

######################################################################################################################    
#  CUSTOMIZE DOMAIN
###################################################################################################################### 
  customize_domain:
    automation:
      initial_state: 'on'

######################################################################################################################    
#  CUSTOMIZER
######################################################################################################################  
customizer:
  custom_ui: local

######################################################################################################################    
#  LOVELACE
###################################################################################################################### 
lovelace:
  mode: yaml

######################################################################################################################    
#  CUSTOM UPDATER
######################################################################################################################   
custom_updater:  

######################################################################################################################    
#  UPDATER
###################################################################################################################### 
updater:

######################################################################################################################    
#  CONFIG
###################################################################################################################### 
config:

######################################################################################################################    
#  HASSIO
###################################################################################################################### 
hassio:

######################################################################################################################    
#  HTTP
###################################################################################################################### 
http:
  api_password: !secret http_password
  server_port: 8123
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 192.168.2.4
    - 192.168.2.3
    - 192.168.2.2
    - 185.128.25.85
  cors_allowed_origins:
    - http://192.168.2.29:7080  
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

######################################################################################################################    
#  FRONTEND
###################################################################################################################### 
frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:   
  extra_html_url_es5:  

######################################################################################################################    
#  CONVERSATION
######################################################################################################################


######################################################################################################################    
#  HISTORY
###################################################################################################################### 


######################################################################################################################    
#  MAP
###################################################################################################################### 
map:

######################################################################################################################    
#  SUN TRACK
###################################################################################################################### 
sun:

######################################################################################################################    
#  WEATHER TRACK
###################################################################################################################### 
weather:
  - platform: darksky
    api_key: !secret dark_sky_key

######################################################################################################################    
#  TEXT TO SPEECH
###################################################################################################################### 
#tts:
#- platform: google

######################################################################################################################    
#  CLOUD
###################################################################################################################### 
#cloud:

######################################################################################################################    
#  YAML FILES
###################################################################################################################### 
group: !include groups.yaml
panel_custom: !include panel_custom.yaml
binary_sensor: !include binary_sensors.yaml
script: !include scripts.yaml
zone: !include zones.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
alarm_control_panel: !include alarm.yaml
automation: !include automations.yaml
device_tracker: !include device_tracker.yaml
recorder: !include recorder.yaml
history: !include history.yaml
######################################################################################################################    
#  DISCOVERY
###################################################################################################################### 
#discovery:
    
######################################################################################################################    
#  CLIMATE
######################################################################################################################     
climate:
  platform: tado  

######################################################################################################################    
#  TADO SMART THERMOSTAT
######################################################################################################################     
tado:
  username: romquenin@gmail.com
  password: !secret tado_password

######################################################################################################################    
#  NETATMO STATION METEO
######################################################################################################################     
netatmo:
  api_key: !secret api_netatmo
  secret_key: !secret secret_netatmo
  username: romquenin@gmail.com
  password: !secret password_netatmo
  discovery: True

######################################################################################################################    
#  DYSON FAN
###################################################################################################################### 
dyson:
  username: romquenin@gmail.com
  password: !secret dyson_password
  language: FR

######################################################################################################################    
#  HARMONY HUB
######################################################################################################################    
remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.2.7
    port: 5222

######################################################################################################################    
#  HUE BRIDGE
######################################################################################################################     
hue:
  bridges:
    - host: 192.168.2.16
 
######################################################################################################################    
#  XIAOMI GATEWAY
######################################################################################################################    
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 78:11:DC:B7:AA:C9  
      key: !secret gateway_key

######################################################################################################################    
#  CAMERA XIAOMI YI
######################################################################################################################   
camera:
  - platform: yi
    name: Salon
    host: '192.168.2.40'
    password: !secret yi_password
    ffmpeg_arguments: '-vf scale=800:450'  

######################################################################################################################    
#  GOOGLE CAST
###################################################################################################################### 
cast:
  media_player:
    - host: 192.168.2.13
    - host: 192.168.2.14

######################################################################################################################    
#  MEDIA PLAYER : AMPLI YAMAHA
######################################################################################################################   
media_player:
  - platform: yamaha_musiccast
    host: 192.168.2.8
    port: 8888

######################################################################################################################    
#  MQTT
######################################################################################################################   
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_name
  password: !secret mqtt_password

######################################################################################################################    
#  ZWAVE
######################################################################################################################   
zwave:
  usb_path: /dev/ttyACM0

######################################################################################################################    
#  WAKE ON LAN
###################################################################################################################### 
wake_on_lan: 

######################################################################################################################    
#  PYTHON SCRIPT
###################################################################################################################### 
python_script:

######################################################################################################################    
#  IFTTT
######################################################################################################################      
ifttt:
  key: !secret ifttt_key

######################################################################################################################    
#  NOTIFY PUSHBULLET
######################################################################################################################    
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

######################################################################################################################    
#  INFLUX DB
######################################################################################################################    
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_name
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state    
 
######################################################################################################################    
#  SABNZBD
######################################################################################################################  
sabnzbd:
  api_key: !secret sab_key
  host: 192.168.2.12
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count   

######################################################################################################################    
#  EMULATED ROKU
######################################################################################################################  
emulated_roku:
  host_ip: 192.168.2.29
  upnp_bind_multicast: True
  listen_ports: 8060

######################################################################################################################    
#  IFRAME
######################################################################################################################   
panel_iframe:
  grafana:
    title: 'Grafana'
    url: 'http://labelrouge.ddns.net:3000'
    icon: mdi:graphql
  synology:
    title: 'DSM'
    url: 'http://labelrouge.ddns.net:5000/'
    icon: mdi:server
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.2.29:3218
  control_panel:
    title: Control Panel
    icon: mdi:view-module
    url: http://192.168.2.29:8123/local/hass.html
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:power-socket-eu
    url: http://192.168.2.29:9541
 