   
   ############################################################
   ##                                                        ##
   ##                     HOME ASSISTANT                     ##
   ##                                                        ##
   ############################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris


##############################################################   
#  https://home-assistant.io/docs/configuration/packages/
##############################################################  
  packages: !include_dir_named config/packages/ 


   ############################################################
   ##                                                        ##
   ##                        CUSTOMIZE                       ##
   ##                                                        ##
   ############################################################

  customize: !include_dir_merge_named customize/


   ############################################################
   ##                                                        ##
   ##                    CUSTOMIZE DOMAIN                    ##
   ##                                                        ##
   ############################################################

  customize_domain:
    automation:
      initial_state: 'on'


   ############################################################
   ##                                                        ##
   ##                         HASSIO                         ##
   ##                                                        ##
   ############################################################

hassio:

   
   ############################################################
   ##                                                        ##
   ##                        CONFIG                          ##
   ##                                                        ##
   ############################################################
 
config:


   ############################################################
   ##                                                        ##
   ##                          HTTP                          ##
   ##                                                        ##
   ############################################################

http:
  api_password: !secret api_password
  base_url: !secret base_url
  server_port: 8123
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks: !secret trusted_networks

 
   ############################################################
   ##                                                        ##
   ##                      FRONTEND                          ##
   ##                                                        ##
   ############################################################
   
frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:   
  extra_html_url_es5:  
  javascript_version: auto


   ############################################################
   ##                                                        ##
   ##                        LOVELACE                        ##
   ##                                                        ##
   ############################################################

lovelace:
  mode: yaml
    

   ############################################################
   ##                                                        ##
   ##                       SUN TRACK                        ##
   ##                                                        ##
   ############################################################
   
sun:


   ############################################################
   ##                                                        ##
   ##                       CLIMATE                          ##
   ##                                                        ##
   ############################################################

climate:       
  platform: tado


   ############################################################
   ##                                                        ##
   ##                          MAP                           ##
   ##                                                        ##
   ############################################################
   
map:
   

   ############################################################
   ##                                                        ##
   ##                          WOL                           ##
   ##                                                        ##
   ############################################################
   
wake_on_lan: 


   ############################################################
   ##                                                        ##
   ##                     PYTHON SCRIPTS                     ##
   ##                                                        ##
   ############################################################
   
python_script: 


   ############################################################
   ##                                                        ##
   ##                     INCLUDE YAML                       ##
   ##                                                        ##
   ############################################################  

alarm_control_panel: !include alarm.yaml
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor/binary_sensors.yaml
group: !include_dir_merge_named group/
input_select: !include_dir_merge_named input_select/
input_boolean: !include input_boolean/input_boolean.yaml
input_number: !include_dir_merge_named input_number/
panel_custom: !include_dir_merge_list panel_custom/
scene: !include_dir_merge_list scene/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
zone: !include zone/zones.yaml
device_tracker: !include_dir_merge_list device_tracker/

recorder: !include recorder.yaml
history: !include history.yaml
panel_iframe: !include components/panel_iframe.yaml
emulated_roku: !include components/emulated_roku.yaml
ifttt: !include components/ifttt.yaml
influxdb: !include components/influxdb.yaml
media_player: !include components/media_player.yaml
sabnzbd: !include components/sabnzbd.yaml
notify: !include components/notify.yaml
custom_updater: !include components/custom_updater.yaml
cast: !include components/cast.yaml
camera: !include components/camera.yaml
xiaomi_aqara: !include components/xiaomi_aqara.yaml
hue: !include components/hue.yaml
remote: !include components/remote.yaml
dyson: !include components/dyson.yaml
netatmo: !include components/netatmo.yaml
tado: !include components/tado.yaml
mqtt: !include components/mqtt.yaml   
zwave: !include components/zwave.yaml
weather: !include components/weather.yaml
logger: !include components/logger.yaml  


   



   


   

 
   

   


   


    
