######################################################################################################################    
#  NMAP
###################################################################################################################### 
- platform: nmap_tracker
  hosts: 
    - 192.168.2.2
    - 192.168.2.3
    - 192.168.2.5    
    - 192.168.2.12
    - 192.168.2.7
    - 192.168.2.9
  home_interval: 2    
  new_device_defaults:
    track_new_devices: false  
  track_new_devices: no
  interval_seconds: 15

######################################################################################################################    
#  BT
###################################################################################################################### 
- platform: bluetooth_tracker
  new_device_defaults:
    track_new_devices: false  
  track_new_devices: no
  consider_home: 180
  interval_seconds: 15

######################################################################################################################    
#  MQTT
###################################################################################################################### 
- platform: mqtt_json
  devices:
    my_device: zanzito/roman_a5/location
- platform: mqtt_json
  devices:
    my_device1: zanzito/roman_tab/location  
  
