
   ############################################################
   ##                                                        ##
   ##                         TPLINK                         ##
   ##                                                        ##
   ############################################################
 
- platform: tplink
  name: TpLink 1
  host: 192.168.2.36

- platform: tplink
  name: TpLink 2
  host: 192.168.2.37


