 
   ############################################################
   ##                                                        ##
   ##                        CAMERA YI                       ##
   ##                                                        ##
   ############################################################

- platform: yi
  name: Salon
  host: '192.168.2.40'
  password: !secret yi_password
  ffmpeg_arguments: '-vf scale=800:450'  