 
   ############################################################
   ##                                                        ##
   ##                      HARMONY HUB                       ##
   ##                                                        ##
   ############################################################
      
- platform: harmony_emu
  name: Harmony Hub
  host: 192.168.2.7
  port: 5222

   