
   ############################################################
   ##                                                        ##
   ##                         GROUP                          ##
   ##                                                        ##
   ############################################################

  ###  group  ###  
group.all_scripts:
  friendly_name: Scripts   
  icon: mdi:script-text-outline 
group.all_automations:
  friendly_name: Automations     
  icon: mdi:home-automation 
group.all_scenes:
  friendly_name: Scènes     
  icon: mdi:palette 


   ############################################################
   ##                                                        ##
   ##                         SWITCH                         ##
   ##                                                        ##
   ############################################################

  ###  SONOFF  ###
switch.sonoff3:
  friendly_name: Switch
switch.sonoff4:
  friendly_name: PS4
switch.sonoff1:
  friendly_name: Apple TV
switch.sonoff2:
  friendly_name: Chromecast

  ###  TPLINK  ###  
switch.tplink_1:
  friendly_name: Tp-Link 1    
switch.tplink_2:
  friendly_name: Tp-Link 2      

  ###  WOL  ###
switch.wake_on_lan:
  friendly_name: PC
  custom_ui_state_card: state-card-custom-ui
   

   ############################################################
   ##                                                        ##
   ##                         SENSOR                         ##
   ##                                                        ##
   ############################################################
   
  ###  PYTHON SCRIPT SUMMARY  ###
sensor.summary:
  friendly_name: Summary
  custom_ui_state_card: state-card-value_only

  ###  SYSTEME  ###   
sensor.derniere_version:   
  icon: mdi:update 
sensor.version:
  friendly_name: Version installée
  icon: mdi:home-assistant  
sensor.processor_use:
  friendly_name: CPU Load
  icon: mdi:chip
sensor.memory_use_percent:
  friendly_name: Memory Use
sensor.disk_free_:
  friendly_name: Disk Free
sensor.memory_free:
  friendly_name: Memory Free 
sensor.cpu_temp:
  friendly_name: Température CPU
sensor.since_last_boot_template:
  friendly_name: Temps d'activité
  icon: mdi:av-timer
sensor.disk_use_percent: 
  friendly_name: Espace disque 

  ###  PRESENCE  ###


  ###  TEMPS  ###
sensor.time:
  friendly_name: Heure actuelle
  icon: mdi:clock      

  ###  SABNZBD  ###
sensor.sabnzbd_status:
  friendly_name: Statut
sensor.sabnzbd_speed:
  friendly_name: Download
  icon: mdi:download
sensor.sabnzbd_left:
  friendly_name: Restant
  icon: mdi:progress-download
sensor.sabnzbd_queue:
  friendly_name: File
  icon: mdi:chart-pie
sensor.sabnzbd_disk_free:
  friendly_name: Libre
  icon: mdi:harddisk   

  ###  TRANSMISSION  ###
sensor.transmission_status:
  friendly_name: Statut
  icon: mdi:eye   
sensor.transmission_down_speed:
  friendly_name: Download
  icon: mdi:download   
sensor.transmission_up_speed:
  friendly_name: Upload
  icon: mdi:upload
sensor.transmission_active_torrents:
  friendly_name: Actif
  icon: mdi:play   
sensor.transmission_paused_torrents:  
  friendly_name: Pause
  icon: mdi:pause


  ###  SYNOLOGY  ###  
sensor.cpu_load_total:
  friendly_name: CPU
sensor.memory_usage_real:
  friendly_name: Memoire
sensor.network_down:
  friendly_name: Download
sensor.network_up:
  friendly_name: Upload
sensor.volume_used_volume_1:
  friendly_name: Disque
  icon: mdi:harddisk      

  ###  DYSON  ###
sensor.salon_temperature:
  friendly_name: Température
  icon: mdi:thermometer    
sensor.salon_humidity:
  friendly_name: Humidité
  icon: mdi:water-percent  
sensor.salon_aqi:
  friendly_name: AQi
sensor.salon_dust:
  friendly_name: Poussière
sensor.salon_filter_life:
  friendly_name: Filtre

  ###  TADO  ###  
sensor.salle_de_bain_humidity:
  friendly_name: Salle de bain humidité
sensor.chambre_humidity:
  friendly_name: Chambre humidité   
sensor.cuisine_humidity:
  friendly_name: Cuisine humidité 

  ###  DARK SKY  ###
sensor.dark_sky_humidity:
  friendly_name: Humidité   

   ###  WAQI  ###  
sensor.waqi_pha10_vrsovice_prague_czech_republic:   
    friendly_name: Qualité de l'air extérieur   
sensor.aqi_friendly:
  extra_badge:
    entity_id: sensor.aqi
  extra_data_template: >-
    var e = 'sensor.aqi_stations_count',
        v = entities[e] !== undefined && parseInt(entities[e].state);
    return v > 1
    ? v + ' stations average'
    : null;
  templates:
    theme: >-
      var e = 'sensor.aqi',
          v = entities[e] !== undefined && parseInt(entities[e].state);
      return v > 100 ? 'card-critical'
      : v > 50 ? 'card-warning'
      : null;
sensor.aqi_nitrogen_dioxide_friendly:
  extra_data_template: >-
    var e = 'sensor.aqi_nitrogen_dioxide';
    return entities[e] !== undefined && entities[e].state != 'unknown'
    ? entities[e].state + ' ' + entities[e].attributes['unit_of_measurement']
    : null;
  templates:
    theme: >-
      var e = 'sensor.aqi_nitrogen_dioxide',
          v = entities[e] !== undefined && parseInt(entities[e].state);
      return v > 100 ? 'card-critical'
      : v > 50 ? 'card-warning'
      : null;
sensor.aqi_ozone_friendly:
  extra_data_template: >-
    var e = 'sensor.aqi_ozone';
    return entities[e] !== undefined && entities[e].state != 'unknown'
    ? entities[e].state + ' ' + entities[e].attributes['unit_of_measurement']
    : null;
  templates:
    theme: >-
      var e = 'sensor.aqi_ozone',
          v = entities[e] !== undefined && parseInt(entities[e].state);
      return v > 100 ? 'card-critical'
      : v > 50 ? 'card-warning'
      : null;
sensor.aqi_particles:
  device_class: pm25
sensor.aqi_particles_friendly:
  extra_data_template: >-
    var e = 'sensor.aqi_particles';
    return entities[e] !== undefined && entities[e].state != 'unknown'
    ? entities[e].state + ' ' + entities[e].attributes['unit_of_measurement']
    : null;
  templates:
    theme: >-
      var e = 'sensor.aqi_particles',
          v = entities[e] !== undefined && parseInt(entities[e].state);
      return v > 100 ? 'card-critical'
      : v > 50 ? 'card-warning'
      : null;
sensor.aqi_sulphur_dioxide_friendly:
  extra_data_template: >-
    var e = 'sensor.aqi_sulphur_dioxide';
    return entities[e] !== undefined && entities[e].state != 'unknown'
    ? entities[e].state + ' ' + entities[e].attributes['unit_of_measurement']
    : null;
  templates:
    theme: >-
      var e = 'sensor.aqi_sulphur_dioxide',
          v = entities[e] !== undefined && parseInt(entities[e].state);
      return v > 100 ? 'card-critical'
      : v > 50 ? 'card-warning'
      : null;
sensor.uv_friendly:
  extra_badge:
    entity_id: sensor.uv
  templates:
    theme: >-
      var e = 'sensor.uv',
          v = entities[e] !== undefined && parseInt(entities[e].state);
      return v >= 6 ? 'card-critical'
      : v >= 3 ? 'card-warning'
      : null;
      
  ###  NETATMO  ###    
sensor.salon_humidity_2:
  friendly_name: Salon humidité     
sensor.netatmo_chambre_humidity_2:
  friendly_name: Chambre Humidité
sensor.netatmo_chambre_temperature_2:
  friendly_name: Chambre Température
sensor.netatmo_salon_co2_2:
  friendly_name: Salon Co2
sensor.netatmo_salon_humidity_2:
  friendly_name: Salon Humidité
sensor.netatmo_salon_noise_2:
  friendly_name: Salon Bruit
sensor.netatmo_salon_pressure_2:
  friendly_name: Salon Pression  
sensor.netatmo_salon_temperature_2:
  friendly_name: Salon Température   
   
  ###  TPLINK  ###  
sensor.tplink_2_current_a:
  friendly_name: actuel     
sensor.tplink_2_current_power_w:
  friendly_name: actuel    
sensor.tplink_2_today_energy_kwh:
  friendly_name: jour
sensor.tplink_2_total_energy_kwh:
  friendly_name: total
sensor.tplink_2_voltage:          
  friendly_name: actuel
sensor.tplink_1_current_a:
  friendly_name: actuel     
sensor.tplink_1_current_power_w:
  friendly_name: actuel    
sensor.tplink_1_today_energy_kwh:
  friendly_name: jour
sensor.tplink_1_total_energy_kwh:  
  friendly_name: total
sensor.tplink_1_voltage:          
  friendly_name: actuel 

  ###  FIXER  ###
sensor.taux_de_change:
  icon: mdi:currency-eur
sensor.taux_de_change_court:
  icon: mdi:currency-eur 
  

   ############################################################
   ##                                                        ##
   ##                      BINARY SENSOR                     ##
   ##                                                        ##
   ############################################################

binary_sensor.door_window_sensor_158d0001de6572:
  friendly_name: Porte d'entrée 
  icon: mdi:door
  templates:
    icon_color: >
      if (state === 'off') return 'rgb(200, 0, 0)';
      return 'rgb(0,200,0)';
   
   
   ############################################################
   ##                                                        ##
   ##                       LUMIÈRES                         ##
   ##                                                        ##
   ############################################################
         
light.astro:
  friendly_name: Astro
  custom_ui_state_card: state-card-custom-ui
  hide_control: false
  show_last_changed: false
  confirm_controls_show_lock: true
light.multi:
  friendly_name: Multi
  custom_ui_state_card: state-card-custom-ui
  hide_control: false
  show_last_changed: false
  confirm_controls_show_lock: true

light.salon:
  friendly_name: Salon
  icon: mdi:sofa
  custom_ui_state_card: state-card-custom-ui
  hide_control: false
  show_last_changed: false
  confirm_controls_show_lock: true      
light.cuisine:
  friendly_name: Cuisine
  icon: mdi:fridge
  custom_ui_state_card: state-card-custom-ui
  hide_control: false
  show_last_changed: false
  confirm_controls_show_lock: true
light.chambre:
  icon: mdi:hotel
  friendly_name: Chambre
  custom_ui_state_card: state-card-custom-ui
  hide_control: false
  show_last_changed: false
  confirm_controls_show_lock: true      
light.entree:
  icon: mdi:door
  friendly_name: Entrée
  custom_ui_state_card: state-card-custom-ui
  hide_control: false
  show_last_changed: false
  confirm_controls_show_lock: true
 
light.gateway_light_7811dcb7aac9:
  friendly_name: Gateway      
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: single-line
  slider_theme:
    min: 0
    max: 100
    pin: true
    off_when_min: false
    report_when_not_changed: false   

   
   ############################################################
   ##                                                        ##
   ##                        SCRIPTS                         ##
   ##                                                        ##
   ############################################################
    
script.1516752539526:
  friendly_name: Redémarrer HASSIO
  icon: mdi:restart

script.play_sel_sound:
  friendly_name: Boucle  
  icon: mdi:loop 

script.play_sel_sound_single:
  friendly_name: Réglage de l'alarme  
  icon: mdi:bell-ring-outline

script.Wakeup:
  icon: mdi:weather-sunset-up
  can_cancel: false
  show_last_changed: true
   

   ############################################################
   ##                                                        ##
   ##                       INPUT SELECT                     ##
   ##                                                        ##
   ############################################################
   
input_select.harmony_hub:
  friendly_name: ACTIVITES
  entity_picture: /local/icons/harmony.jpg

input_select.ha_mode:
  friendly_name: Profils
  entity_picture: /local/badges/roman.jpg 

input_select.hass_theme:
  friendly_name: Themes
  entity_picture: /local/icons/theme.png

input_select.tv_input_select:
  entity_picture: /local/icons/samsung.png     

input_select.amp_input_select:
  entity_picture: /local/icons/yamaha.png   

   
   ############################################################
   ##                                                        ##
   ##                      MEDIA PLAYER                      ##
   ##                                                        ##
   ############################################################
    
media_player.home_cinema_main:
  friendly_name: Yamaha  

media_player.googlehome1472:
  friendly_name: Google Home

media_player.googlehome0840:
  friendly_name: Google Home Mini 

   
   ############################################################
   ##                                                        ##
   ##                      INPUT NUMBER                      ##
   ##                                                        ##
   ############################################################
         
input_number.dyson_fan_speed:
  friendly_name: Vitesse
  entity_picture: /local/icons/dysonpicblue.png  


   
   ############################################################
   ##                                                        ##
   ##                   ALARM CONTROL PANEL                  ##
   ##                                                        ##
   ############################################################
       
alarm_control_panel.maison:
  friendly_name: Maison
  icon: mdi:shield-outline     
  
  
  
  
