   
   ############################################################
   ##                                                        ##
   ##                  VITESSE VENTILATEUR                   ##
   ##                                                        ##
   ############################################################

dyson_fan_speed:
  icon: mdi:fan
  name: Speed
  initial: 1
  min: 1
  max: 10
  step: 1

   
   ############################################################
   ##                                                        ##
   ##                     GATEWAY VOLUME                     ##
   ##                                                        ##
   ############################################################

  ### Input number pour controler le volume du GATEWAY ###
gateway_volume:
  name: Volume
  initial: 10
  min: 0
  max: 100
  step: 2
  icon: mdi:volume-high

  ### Input number pour regler la duree de la boucle ###
loop_delay:
  name: "Durée"
  initial: 3
  min: 0
  max: 15
  step: 1
  icon: mdi:fast-forward-outline
   

   ############################################################
   ##                                                        ##
   ##                       RÉVEIL                           ##
   ##                                                        ##
   ############################################################

alarmclock_wd_hour:
  name: Heure
  icon: mdi:timer
  initial: 7
  min: 0
  max: 23
  step: 1
  
alarmclock_wd_minute:
  name: Minute
  icon: mdi:timer
  initial: 30
  min: 0
  max: 55
  step: 5  
  