   
   ############################################################
   ##                                                        ##
   ##                        ALARME                          ##
   ##                                                        ##
   ############################################################

- name: Alarm
  entities:
    light.gateway_light_7811dcb7aac9:        
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]
    light.bloom_1:    
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]
    light.strip_1:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]
    light.lamp_2:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]
    light.lamp_1:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]  
    light.lamp_3:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]        
    light.living:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0] 
    light.spot_1:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]   
    light.spot_2:
      state: on
      brightness_pct: 100
      rgb_color: [255,0,0]   
     
   
   ############################################################
   ##                                                        ##
   ##                   LIVINGROOM NORMAL                    ##
   ##                                                        ##
   ############################################################

- name: Livingroom normal
  entities:
    light.bloom_1:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 80
    light.strip_1:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 80
    light.lamp_2:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 80
    light.lamp_1:
      state: off
      transition: 4         
    light.living:
      state: off
      transition: 4            
    light.spot_1:
      state: off
      transition: 4            
    light.spot_2:
      state: off
      transition: 4 

   
   ############################################################
   ##                                                        ##
   ##                    LIVINGROOM DIM                      ##
   ##                                                        ##
   ############################################################

- name: Livingroom dim
  entities:
    light.bloom_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 70
    light.strip_1:
      profile: relax        
      state: on
      transition: 8
      brightness_pct: 35
    light.lamp_2:
      profile: relax        
      state: on
      transition: 8
      brightness_pct: 25
    light.lamp_1:
      state: off
      transition: 4         
    light.living:
      state: off
      transition: 4            
    light.spot_1:
      state: off
      transition: 4            
    light.spot_2:
      state: off
      transition: 4 

   
   ############################################################
   ##                                                        ##
   ##                    LIVINGROOM OFF                      ##
   ##                                                        ##
   ############################################################
              
- name: Livingroom off
  entities:
    light.bloom_1:
      state: off
      transition: 4        
    light.strip_1:
      state: off
      transition: 4
    light.lamp_1:
      state: off
      transition: 4        
    light.lamp_2:
      state: off
      transition: 4        
    light.living:
      state: off
      transition: 4      
    light.spot_1:
      state: off
      transition: 4       
    light.spot_2:
      state: off
      transition: 4    

   
   ############################################################
   ##                                                        ##
   ##                       PRINTEMPS                        ##
   ##                                                        ##
   ############################################################

- name: Printemps
  entities:
    light.bloom_1:    
      state: on
      rgb_color: [255,150,184]
      brightness: 217      
      transition: 6
    light.strip_1:
      state: on
      rgb_color: [255,150,184]
      brightness: 217      
      transition: 6
    light.lamp_2:
      state: on
      rgb_color: [255,186,209]
      brightness: 217      
      transition: 6 
    light.lamp_1:
      state: on
      rgb_color: [255,150,184]
      brightness: 217      
      transition: 6       
    light.living:
      state: on
      rgb_color: [255,150,184]
      brightness: 217      
      transition: 6         
    light.spot_1:
      state: on
      rgb_color: [255,186,209]
      brightness: 217      
      transition: 6             
    light.spot_2:
      state: on
      rgb_color: [255,186,209]
      brightness: 217      
      transition: 6 

   
   ############################################################
   ##                                                        ##
   ##                        TROPICAL                        ##
   ##                                                        ##
   ############################################################

- name: Tropical
  entities:
    light.bloom_1:    
      state: on
      rgb_color: [236,149,70]
      brightness: 113      
      transition: 6
    light.strip_1:
      state: on
      rgb_color: [236,149,70]

      brightness: 113      
      transition: 6
    light.lamp_2:
      state: on
      rgb_color: [236,149,70]
      brightness: 113      
      transition: 6
    light.lamp_1:
      state: on
      rgb_color: [194,163,244]
      brightness: 113      
      transition: 6         
    light.living:
      state: on
      rgb_color: [194,163,244]
      brightness: 113      
      transition: 6         
    light.spot_1:
      state: on
      rgb_color: [194,163,244]
      brightness: 113      
      transition: 6             
    light.spot_2:
      state: on
      rgb_color: [194,163,244]
      brightness: 113      
      transition: 6       
   

   ############################################################
   ##                                                        ##
   ##                        BOREALE                         ##
   ##                                                        ##
   ############################################################

- name: Boreale
  entities:
    light.bloom_1:    
      state: on
      rgb_color: [68,225,216]
      brightness: 142      
      transition: 6
    light.strip_1:
      state: on
      rgb_color: [68,225,216]
      brightness: 142      
      transition: 6
    light.lamp_2:
      state: on
      rgb_color: [184,180,255]
      brightness: 143      
      transition: 6 
    light.lamp_1:
      state: on
      rgb_color: [68,225,216]
      brightness: 142      
      transition: 6         
    light.living:
      state: on
      rgb_color: [68,225,216]
      brightness: 142      
      transition: 6        
    light.spot_1:
      state: on
      rgb_color: [184,180,255]
      brightness: 143      
      transition: 6           
    light.spot_2:
      state: on
      rgb_color: [184,180,255]
      brightness: 143      
      transition: 6 

   
   ############################################################
   ##                                                        ##
   ##                        SAVANE                          ##
   ##                                                        ##
   ############################################################
 
- name: Savane
  entities:
    light.bloom_1:    
      state: on
      rgb_color: [255,94,37]
      brightness: 205      
      transition: 6 
    light.strip_1:
      state: on
      rgb_color: [255,94,37]
      brightness: 205      
      transition: 6 
    light.lamp_2:
      state: on
      rgb_color: [255,159,81]
      brightness: 204      
      transition: 6 
    light.lamp_1:
      state: on
      rgb_color: [255,159,81]
      brightness: 204      
      transition: 6        
    light.living:
      state: on
      rgb_color: [255,94,37]
      brightness: 205      
      transition: 6        
    light.spot_1:
      state: on
      rgb_color: [255,159,81]
      brightness: 204      
      transition: 6         
    light.spot_2:
      state: on
      rgb_color: [255,159,81]
      brightness: 204      
      transition: 6 

   
   ############################################################
   ##                                                        ##
   ##                           DIM                          ##
   ##                                                        ##
   ############################################################
      
- name: Dim
  entities:
    light.bloom_1:    
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50
    light.strip_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50
    light.lamp_2:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50
    light.lamp_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50      
    light.living:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50      
    light.spot_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50       
    light.spot_2:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 50
 
   
   ############################################################
   ##                                                        ##
   ##                       SUPER DIM                        ##
   ##                                                        ##
   ############################################################
     
- name: Super Dim
  entities:
    light.bloom_1:    
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20
    light.strip_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20
    light.lamp_2:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20
    light.lamp_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20      
    light.living:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20      
    light.spot_1:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20       
    light.spot_2:
      profile: relax
      state: on
      transition: 8
      brightness_pct: 20  

   
   ############################################################
   ##                                                        ##
   ##                        DETENTE                         ##
   ##                                                        ##
   ############################################################
  
- name: Detente
  entities:
    light.bloom_1:    
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65
    light.strip_1:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65
    light.lamp_2:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65
    light.lamp_1:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65   
    light.living:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65    
    light.spot_1:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65     
    light.spot_2:
      profile: reading        
      state: on
      transition: 6
      brightness_pct: 65
      