   
   ############################################################
   ##                                                        ##
   ##                    WAKE ON LINE                        ##
   ##                                                        ##
   ############################################################

- platform: wake_on_lan
  mac_address: "4C-CC-6A-67-52-EE"
  host: 192.168.2.10
  turn_off:
      service: hassio.addon_stdin
      data:
          addon: core_rpc_shutdown
          input: roman
   

   ############################################################
   ##                                                        ##
   ##                         TPLINK                         ##
   ##                                                        ##
   ############################################################
 
- platform: tplink
  name: TpLink 1
  host: 192.168.2.36

- platform: tplink
  name: TpLink 2
  host: 192.168.2.37

   
   ############################################################
   ##                                                        ##
   ##                    HA MODE PROFILS DEV                 ##
   ##                                                        ##
   ############################################################

- platform: template
  switches:
    mode_developer:
      value_template: "{{ is_state('input_select.ha_mode', 'Developer') }}"
      turn_on:
        - service: script.mode_developer
      turn_off:
        - service: script.mode_normal
   

   ############################################################
   ##                                                        ##
   ##                        SONOFF                          ##
   ##                                                        ##
   ############################################################

  ###  SONOFF  ###
- platform: mqtt
  name: "Sonoff"
  state_topic: "stat/sonoff/POWER"
  command_topic: "cmnd/sonoff/POWER"
  availability_topic: "tele/sonoff/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Sonoff1"
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/POWER"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Sonoff2"
  state_topic: "stat/sonoff2/POWER"
  command_topic: "cmnd/sonoff2/POWER"
  availability_topic: "tele/sonoff2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Sonoff3"
  state_topic: "stat/sonoff3/POWER"
  command_topic: "cmnd/sonoff3/POWER"
  availability_topic: "tele/sonoff3/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Sonoff4"
  state_topic: "stat/sonoff4/POWER"
  command_topic: "cmnd/sonoff4/POWER"
  availability_topic: "tele/sonoff4/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
#- platform: mqtt
 # name: "Room"
 # state_topic: "stat/sonoffTemp/POWER"
 # command_topic: "cmnd/sonoffTemp/POWER"
 # availability_topic: "tele/sonoffTemp/LWT"
 # qos: 1
 # payload_on: "ON"
 # payload_off: "OFF"
 # payload_available: "Online"
 # payload_not_available: "Offline"
 # retain: true
