   
   ############################################################
   ##                                                        ##
   ##                         SONARR                         ##
   ##                                                        ##
   ############################################################
  
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_key
  host: 192.168.2.12
  port: 8989
  days: 7
  ssl: false
  max: 5

   

