   
   ############################################################
   ##                                                        ##
   ##                         NMAP                           ##
   ##                                                        ##
   ############################################################

- platform: nmap_tracker
  hosts: 
    - 192.168.2.2
    - 192.168.2.3
   # - 192.168.2.5    
    - 192.168.2.12
    - 192.168.2.7
    - 192.168.2.9
  home_interval: 2    
  new_device_defaults:
    track_new_devices: false  
  track_new_devices: no
  interval_seconds: 30

